In [9]:
import numpy as np
import math
tmp = np.sqrt(math.pi)
print(tmp)
tmp = np.sqrt(np.pi)
print(tmp)


1.7724538509055159
1.7724538509055159


In [10]:
def generate_array(L=400, k=20, a=98.5):
    # Create an array of length L filled with zeros
    arr = np.zeros(L)
    
    # Fill the array according to the specified pattern
    for i in range(0, L, k):
        arr[i:i+k] = a + (i // k) * 0.25
    
    return arr

# Example usage
result = generate_array()
print(result)

[ 98.5   98.5   98.5   98.5   98.5   98.5   98.5   98.5   98.5   98.5
  98.5   98.5   98.5   98.5   98.5   98.5   98.5   98.5   98.5   98.5
  98.75  98.75  98.75  98.75  98.75  98.75  98.75  98.75  98.75  98.75
  98.75  98.75  98.75  98.75  98.75  98.75  98.75  98.75  98.75  98.75
  99.    99.    99.    99.    99.    99.    99.    99.    99.    99.
  99.    99.    99.    99.    99.    99.    99.    99.    99.    99.
  99.25  99.25  99.25  99.25  99.25  99.25  99.25  99.25  99.25  99.25
  99.25  99.25  99.25  99.25  99.25  99.25  99.25  99.25  99.25  99.25
  99.5   99.5   99.5   99.5   99.5   99.5   99.5   99.5   99.5   99.5
  99.5   99.5   99.5   99.5   99.5   99.5   99.5   99.5   99.5   99.5
  99.75  99.75  99.75  99.75  99.75  99.75  99.75  99.75  99.75  99.75
  99.75  99.75  99.75  99.75  99.75  99.75  99.75  99.75  99.75  99.75
 100.   100.   100.   100.   100.   100.   100.   100.   100.   100.
 100.   100.   100.   100.   100.   100.   100.   100.   100.   100.
 100.25 100.25 100

In [2]:
def dist1(phi_1,phi_2):
    d = np.abs(phi_1 - phi_2)
    d = np.where(d > np.pi, 2 * np.pi - d, d)
    return d

def dist2(phi_1,phi_2):
    dis = phi_1 - phi_2
    dis[dis > np.pi] -= 2 * np.pi
    dis[dis < -np.pi] += 2 * np.pi
    return dis

def dist3(phi_1,phi_2):
    d = phi_1 - phi_2
    d = np.where(d > np.pi, d - 2 * np.pi, d)
    d = np.where(d < -np.pi, d + 2 * np.pi, d)
    return d


In [3]:
phi_1 = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
phi_2 = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi]) + np.pi/4
print(dist1(phi_1,phi_2))
print(dist2(phi_1,phi_2))
print(dist3(phi_1,phi_2))

[0.78539816 0.78539816 0.78539816 0.78539816 0.78539816]
[-0.78539816 -0.78539816 -0.78539816 -0.78539816 -0.78539816]
[-0.78539816 -0.78539816 -0.78539816 -0.78539816 -0.78539816]


In [9]:

def position2phase_modules(x):
    Lphase = 3
    lambda_gs = np.array([1, 2, 4])
    phi_g = (x[:,None]/lambda_gs ) % Lphase
    return phi_g

x = np.array([4,10])
print(position2phase_modules(x))

[[1.  2.  1. ]
 [1.  2.  2.5]]


In [15]:
import torch
theta = torch.linspace(-1, 5, 3)
theta_expand = theta[None,:,None].expand(2,3,2)
# do clamp for the elements of theta_expand
theta_clamp = torch.clamp(theta_expand, min=0)
print(theta_clamp)

tensor([[[0., 0.],
         [2., 2.],
         [5., 5.]],

        [[0., 0.],
         [2., 2.],
         [5., 5.]]])


In [18]:
phase = torch.ones([2,3,2])
theta = torch.ones([3,2]) *2
angle = phase + theta
print(angle)
print('angle shape:', angle.shape)


tensor([[[3., 3.],
         [3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.],
         [3., 3.]]])
angle shape: torch.Size([2, 3, 2])


In [10]:
import numpy as np
import itertools


def sum_probabilities(prob_matrix):
    n, m = prob_matrix.shape
    # Generate all possible index combinations where each element comes from a different module
    index_combinations = itertools.product(range(n), repeat=m)
    
    # Calculate the sum of probabilities for each combination
    prob_sums = []
    for combination in index_combinations:
        prob_sum = sum(prob_matrix[combination[i], i] for i in range(m))
        prob_sums.append(prob_sum)
    
    return np.array(prob_sums)

# Example usage
prob_matrix = np.array([[0., 0.1, 0.2],
                        [0.4, 0.0, 5.0],
                        [0.6, 1.1, 0.0]])

result = sum_probabilities(prob_matrix)
print(result.shape)
print(result)



(27,)
[0.3 5.1 0.1 0.2 5.  0.  1.3 6.1 1.1 0.7 5.5 0.5 0.6 5.4 0.4 1.7 6.5 1.5
 0.9 5.7 0.7 0.8 5.6 0.6 1.9 6.7 1.7]


In [23]:
import numpy as np
import itertools

def sum_probabilities(prob_matrix):
    n, m = prob_matrix.shape
    # Generate all possible index combinations where each element comes from a different module
    index_combinations = list(itertools.product(range(n), repeat=m))
    
    # Calculate the sum of probabilities for each combination
    prob_sums = []
    for combination in index_combinations:
        prob_sum = sum(prob_matrix[combination[i], i] for i in range(m))
        prob_sums.append(prob_sum)
    
    prob_sums = np.array(prob_sums)
    
    # Find the maximum probability sum and its corresponding indices
    max_prob_sum = np.max(prob_sums)
    max_index = np.argmax(prob_sums)
    max_combination = index_combinations[max_index]
    
    # Convert the max_combination to the required format [candidate_index, module_index]
    # max_combination_indices = [(max_combination[i], i) for i in range(m)]
    max_combination_indices = [max_combination[i] for i in range(m)]
    
    return prob_sums, max_prob_sum, max_combination_indices

# Example usage
prob_matrix = np.array([[0.1, 0.2, 0.3],
                        [0.4, 0.5, 0.6],
                        [0.7, 0.8, 0.9]])

prob_sums, max_prob_sum, max_combination_indices = sum_probabilities(prob_matrix)
print("Probability Sums:", prob_sums)
print("Maximum Probability Sum:", max_prob_sum)
print("Indices of Maximum Combination:", max_combination_indices)


Probability Sums: [0.6 0.9 1.2 0.9 1.2 1.5 1.2 1.5 1.8 0.9 1.2 1.5 1.2 1.5 1.8 1.5 1.8 2.1
 1.2 1.5 1.8 1.5 1.8 2.1 1.8 2.1 2.4]
Maximum Probability Sum: 2.4
Indices of Maximum Combination: [2, 2, 2]


In [24]:
import numpy as np

def max_probabilities(prob_matrix):
    # Find the maximum probability value for each column
    max_prob_values = np.max(prob_matrix, axis=0)
    # Find the index of the maximum probability value for each column
    max_prob_indices = np.argmax(prob_matrix, axis=0)
    
    return max_prob_values, max_prob_indices

# Example usage
prob_matrix = np.array([[0.1, 0.2, 0.3],
                        [0.4, 0.5, 0.6],
                        [0.7, 0.8, 0.9]])

max_prob_values, max_prob_indices = max_probabilities(prob_matrix)
print("Maximum Probability Values:", max_prob_values)
print("Indices of Maximum Probabilities:", max_prob_indices)


Maximum Probability Values: [0.7 0.8 0.9]
Indices of Maximum Probabilities: [2 2 2]


In [27]:
# torch version
def max_probabilities(prob_matrix):
    # Find the maximum probability value for each column
    max_prob_values = torch.max(prob_matrix, dim=0).values
    # Find the index of the maximum probability value for each column
    max_prob_indices = torch.argmax(prob_matrix, dim=0)

    return max_prob_values, max_prob_indices

# Example usage
prob_matrix = torch.tensor([[0.1, 0.2, 0.3],
                            [0.4, 0.5, 0.6],
                            [0.7, 0.8, 0.9]])

max_prob_values, max_prob_indices = max_probabilities(prob_matrix)
print("Maximum Probability Values:", max_prob_values)
print("Indices of Maximum Probabilities:", max_prob_indices)

Maximum Probability Values: tensor([0.7000, 0.8000, 0.9000])
Indices of Maximum Probabilities: tensor([2, 2, 2])


In [32]:

def read_MAP_indices_max(log_posterior):
    '''
    log_posterior shape [n_pos, n_phi, M]
    Note: we can compress log_posterior from [n_pos, n_phi, n_phi, ..., n_phi] to [n_pos, n_phi, M] 
            because different modules are independent, covariance matrix is diagonal, 
            non-diagonal combinations are abandoned.
    '''
    n_pos, n_phi, M = log_posterior.shape
    # initialize max_log_posterior as negative infinity
    max_log_posterior = -np.inf
    z_est_index = -1.5 # use fractional number make it not index-like for initialization
    phi_est_index = np.ones(M) * -1.5 # use fractional number make it not index-like for initialization
    for i in range(n_pos):
        max_prob_values = np.max(log_posterior[i,:,:], axis=0)
        # Find the index of the maximum probability value for each column
        max_prob_indices = np.argmax(log_posterior[i,:,:], axis=0)
        max_prob_sum = np.sum(max_prob_values)
        if max_prob_sum > max_log_posterior:
            max_log_posterior = max_prob_sum
            z_est_index = i
            for j in range(M):
                phi_est_index[j] = max_prob_indices[j]
    return z_est_index, phi_est_index

def read_MAP_indices_max_vec(log_posterior):
    '''
    log_posterior shape [n_pos, n_phi, M]
    Note: we can compress log_posterior from [n_pos, n_phi, n_phi, ..., n_phi] to [n_pos, n_phi, M] 
            because different modules are independent, covariance matrix is diagonal, 
            non-diagonal combinations are abandoned.
    '''
    n_pos, n_phi, M = log_posterior.shape
    # Calculate the maximum probability values and their indices for each [n_phi, M] matrix
    max_prob_values = np.max(log_posterior, axis=1)
    max_prob_indices = np.argmax(log_posterior, axis=1)
    # Sum the maximum probability values across the M modules for each position
    max_prob_sums = np.sum(max_prob_values, axis=1)
    # Find the position with the highest sum of maximum probabilities
    z_est_index = np.argmax(max_prob_sums)
    max_log_posterior = max_prob_sums[z_est_index]
    phi_est_index = max_prob_indices[z_est_index]
    
    return z_est_index, phi_est_index

In [33]:
log_posterior = np.random.rand(100, 5, 3)  # Example random log posterior
z_est_index, phi_est_index = read_MAP_indices_max(log_posterior)
print("Z Estimated Index:", z_est_index)
print("Phi Estimated Indices:", phi_est_index)

z_est_index, phi_est_index = read_MAP_indices_max_vec(log_posterior)
print("Z Estimated Index:", z_est_index)
print("Phi Estimated Indices:", phi_est_index)

Z Estimated Index: 26
Phi Estimated Indices: [3. 3. 4.]
Z Estimated Index: 26
Phi Estimated Indices: [3 3 4]


In [22]:
import torch

# Define the original 1D tensor
n_phi = 3  # Example size
M = 4  # Example value for M
tensor_1d = torch.arange(n_phi)  # Example tensor, e.g., tensor([0, 1, 2, 3])

# Expand/repeat to shape [n_phi, n_phi, ..., n_phi] with M n_phi dimensions
# Method 1
new_shape = (n_phi,) * M  # Create a tuple with M elements, each equal to n_phi
# Use view to create the target shape
expanded_tensor1 = tensor_1d.expand(new_shape)
# print('expanded_tensor1',expanded_tensor1)
print('expanded_tensor1 shape:',expanded_tensor1.shape)

# Method 2
new_shape = (n_phi,) * M
expanded_tensor2 = tensor_1d.view((n_phi,) + (1,) * (M-1)).expand((n_phi,) * M)

# print('expanded_tensor2',expanded_tensor2)
print('expanded_tensor2 shape:',expanded_tensor2.shape)

print(expanded_tensor1[:,0,0,0])
print(expanded_tensor2[:,0,0,0])

expanded_tensor1 shape: torch.Size([3, 3, 3, 3])
expanded_tensor2 shape: torch.Size([3, 3, 3, 3])
tensor([0, 0, 0])
tensor([0, 1, 2])


In [6]:
import torch

n_phi = 4  # Example size
tensor_1d = torch.arange(n_phi)  # Example tensor, e.g., tensor([0, 1, 2, 3])

# Reshape the tensor to the target shape
# We first unsqueeze the tensor to add the necessary dimensions, then expand it
target_shape = (n_phi,) * (M)  # We add one extra dimension to prepare for expansion
expanded_tensor = tensor_1d.view(n_phi, 1, 1).expand(target_shape)

print(expanded_tensor.shape)


torch.Size([4, 4, 4])


In [5]:
import numpy as np
# give a 3D array
fg = np.random.rand(3, 4, 5)
T = 2
# I_grid = np.repeat(fg[np.newaxis, :, :], T, axis=0)
I_grid = np.repeat(fg[np.newaxis, :], T, axis=0)
print(I_grid.shape)
print(I_grid)

(2, 3, 4, 5)
[[[[0.5327366  0.11480593 0.71479157 0.19814841 0.88423634]
   [0.52995703 0.08362037 0.62838849 0.73335462 0.39867761]
   [0.18316769 0.07116311 0.75529286 0.33697866 0.98965596]
   [0.1388822  0.31271939 0.26973765 0.91575173 0.40839157]]

  [[0.34241974 0.01864925 0.76281074 0.78996726 0.43707759]
   [0.78489274 0.41305717 0.84112265 0.51995033 0.3365053 ]
   [0.30141437 0.35487992 0.15687012 0.56402792 0.40840798]
   [0.42288143 0.65302685 0.34177966 0.49998604 0.73951258]]

  [[0.17528032 0.78234869 0.91140511 0.16397892 0.20531616]
   [0.43437259 0.15946907 0.98878234 0.82016337 0.32884067]
   [0.80875212 0.40833374 0.39924381 0.68418995 0.18962845]
   [0.78433334 0.04854868 0.60332843 0.50932853 0.41249328]]]


 [[[0.5327366  0.11480593 0.71479157 0.19814841 0.88423634]
   [0.52995703 0.08362037 0.62838849 0.73335462 0.39867761]
   [0.18316769 0.07116311 0.75529286 0.33697866 0.98965596]
   [0.1388822  0.31271939 0.26973765 0.91575173 0.40839157]]

  [[0.34241974 0.

In [6]:
len_Igrid = I_grid.shape[0]
I_grid[int(len_Igrid/2):,:] = 0
print(I_grid)

[[[[0.5327366  0.11480593 0.71479157 0.19814841 0.88423634]
   [0.52995703 0.08362037 0.62838849 0.73335462 0.39867761]
   [0.18316769 0.07116311 0.75529286 0.33697866 0.98965596]
   [0.1388822  0.31271939 0.26973765 0.91575173 0.40839157]]

  [[0.34241974 0.01864925 0.76281074 0.78996726 0.43707759]
   [0.78489274 0.41305717 0.84112265 0.51995033 0.3365053 ]
   [0.30141437 0.35487992 0.15687012 0.56402792 0.40840798]
   [0.42288143 0.65302685 0.34177966 0.49998604 0.73951258]]

  [[0.17528032 0.78234869 0.91140511 0.16397892 0.20531616]
   [0.43437259 0.15946907 0.98878234 0.82016337 0.32884067]
   [0.80875212 0.40833374 0.39924381 0.68418995 0.18962845]
   [0.78433334 0.04854868 0.60332843 0.50932853 0.41249328]]]


 [[[0.         0.         0.         0.         0.        ]
   [0.         0.         0.         0.         0.        ]
   [0.         0.         0.         0.         0.        ]
   [0.         0.         0.         0.         0.        ]]

  [[0.         0.         0.  